// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SimulaGGs
Rcpp::List SimulaGGs(Rcpp::IntegerVector NDatos, Rcpp::NumericVector Programa, Rcpp::NumericVector Par);
RcppExport SEXP _QueueSimulator_SimulaGGs(SEXP NDatosSEXP, SEXP ProgramaSEXP, SEXP ParSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type NDatos(NDatosSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Programa(ProgramaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Par(ParSEXP);
    rcpp_result_gen = Rcpp::wrap(SimulaGGs(NDatos, Programa, Par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QueueSimulator_SimulaGGs", (DL_FUNC) &_QueueSimulator_SimulaGGs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_QueueSimulator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
