# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SimulaGGs <- function(NDatos, Programa, dist_atencion, param_atencion, dist_llegadas, param_llegadas) {
    .Call(`_QueueSimulator_SimulaGGs`, NDatos, Programa, dist_atencion, param_atencion, dist_llegadas, param_llegadas)
}

