# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_matrix <- function(n) {
    .Call(`_QueueSimulator_create_matrix`, n)
}

sim_mc <- function(P, transition_matrix, seed, init) {
    .Call(`_QueueSimulator_sim_mc`, P, transition_matrix, seed, init)
}

